// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT1BWphOVw_gbbmXD7Njy4CajbnIxQx1s',
    appId: '1:319570273346:web:44cb9cdae092d3b2d1f9db',
    messagingSenderId: '319570273346',
    projectId: 'agent-ai-ce692',
    authDomain: 'agent-ai-ce692.firebaseapp.com',
    storageBucket: 'agent-ai-ce692.firebasestorage.app',
    measurementId: 'G-NC89J56K69',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNDuUyYBVXWgWnToDqArbcVuG99IteD-Q',
    appId: '1:319570273346:android:44e5fcbfa3ac8d6cd1f9db',
    messagingSenderId: '319570273346',
    projectId: 'agent-ai-ce692',
    storageBucket: 'agent-ai-ce692.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuip1dDprvUTM2-5SdLAc6nL6KvpBLAPs',
    appId: '1:319570273346:ios:e58db6fb62e563c7d1f9db',
    messagingSenderId: '319570273346',
    projectId: 'agent-ai-ce692',
    storageBucket: 'agent-ai-ce692.firebasestorage.app',
    iosBundleId: 'com.example.agentAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuip1dDprvUTM2-5SdLAc6nL6KvpBLAPs',
    appId: '1:319570273346:ios:e58db6fb62e563c7d1f9db',
    messagingSenderId: '319570273346',
    projectId: 'agent-ai-ce692',
    storageBucket: 'agent-ai-ce692.firebasestorage.app',
    iosBundleId: 'com.example.agentAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT1BWphOVw_gbbmXD7Njy4CajbnIxQx1s',
    appId: '1:319570273346:web:1a8477d706752400d1f9db',
    messagingSenderId: '319570273346',
    projectId: 'agent-ai-ce692',
    authDomain: 'agent-ai-ce692.firebaseapp.com',
    storageBucket: 'agent-ai-ce692.firebasestorage.app',
    measurementId: 'G-SEMD4STLCF',
  );
}
